/**
 * 大使模块 SQL（7张表）
 */

module.exports = [
  // ambassador_applications 表
  `CREATE TABLE IF NOT EXISTS ambassador_applications (
    id INT AUTO_INCREMENT PRIMARY KEY COMMENT '申请ID',
    user_id INT NOT NULL COMMENT '用户ID',
    user_uid VARCHAR(64) COMMENT '用户UID',
    _openid VARCHAR(64) DEFAULT '' NOT NULL COMMENT 'CloudBase 用户标识（用于数据隔离）',
    real_name VARCHAR(50) NOT NULL COMMENT '真实姓名',
    phone VARCHAR(20) NOT NULL COMMENT '手机号',
    wechat_id VARCHAR(50) COMMENT '微信号',
    city VARCHAR(50) COMMENT '所在城市',
    occupation VARCHAR(50) COMMENT '职业/行业',
    apply_reason TEXT COMMENT '申请原因',
    understanding TEXT COMMENT '对天道文化的理解',
    willing_help TINYINT(1) DEFAULT 1 COMMENT '是否愿意帮助他人',
    promotion_plan TEXT COMMENT '推广计划',
    status TINYINT DEFAULT 0 COMMENT '状态：0待审核/1待面试/2面试中/3已通过/4已拒绝',
    interview_time DATETIME COMMENT '面试时间',
    interview_remark VARCHAR(500) COMMENT '面试备注',
    reject_reason VARCHAR(500) COMMENT '拒绝原因',
    audit_admin_id INT COMMENT '审核管理员ID',
    audit_time DATETIME COMMENT '审核时间',
    audit_remark VARCHAR(500) COMMENT '审核备注',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '申请时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_user_id (user_id),
    INDEX idx_status (status),
    INDEX idx_audit_admin_id (audit_admin_id),
    INDEX idx_created_at (created_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='大使申请表'`,

  // ambassador_quotas 表
  `CREATE TABLE IF NOT EXISTS ambassador_quotas (
    id INT AUTO_INCREMENT PRIMARY KEY COMMENT '名额ID',
    user_id INT NOT NULL COMMENT '大使用户ID',
    user_uid VARCHAR(64) COMMENT '大使用户UID',
    _openid VARCHAR(64) DEFAULT '' NOT NULL COMMENT 'CloudBase 用户标识（用于数据隔离）',
    ambassador_level TINYINT NOT NULL COMMENT '大使等级：2青鸾/3鸿鹄/4金凤等',
    quota_type TINYINT NOT NULL COMMENT '名额类型：1初探班/2密训班',
    source_type TINYINT NOT NULL COMMENT '来源类型：1大使升级/2活动奖励/3系统发放',
    source_remark VARCHAR(200) COMMENT '来源说明',
    total_quantity INT NOT NULL COMMENT '总数量',
    used_quantity INT DEFAULT 0 COMMENT '已使用数量',
    remaining_quantity INT NOT NULL COMMENT '剩余数量',
    expire_date DATE NOT NULL COMMENT '过期日期',
    status TINYINT DEFAULT 1 COMMENT '状态：0失效/1有效',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_user_id (user_id),
    INDEX idx_ambassador_level (ambassador_level),
    INDEX idx_quota_type (quota_type),
    INDEX idx_source_type (source_type),
    INDEX idx_expire_date (expire_date),
    INDEX idx_status (status),
    INDEX idx_user_status (user_id, status)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='大使名额表'`,

  // quota_usage_records 表
  `CREATE TABLE IF NOT EXISTS quota_usage_records (
    id INT AUTO_INCREMENT PRIMARY KEY COMMENT '记录ID',
    quota_id INT NOT NULL COMMENT '名额ID',
    ambassador_id INT NOT NULL COMMENT '大使用户ID',
    ambassador_uid VARCHAR(64) COMMENT '大使用户UID',
    _openid VARCHAR(64) DEFAULT '' NOT NULL COMMENT 'CloudBase 用户标识（用于数据隔离）',
    recipient_id INT COMMENT '受赠人用户ID',
    recipient_uid VARCHAR(64) COMMENT '受赠人用户UID',
    recipient_name VARCHAR(50) COMMENT '受赠人姓名',
    recipient_phone VARCHAR(20) COMMENT '受赠人手机号',
    usage_type TINYINT NOT NULL COMMENT '使用类型：1赠送/2核销',
    course_id INT COMMENT '课程ID',
    course_name VARCHAR(100) COMMENT '课程名称',
    status TINYINT DEFAULT 1 COMMENT '状态：1已赠送/2已核销/3已取消',
    verify_time DATETIME COMMENT '核销时间',
    verify_admin_id INT COMMENT '核销管理员ID',
    message VARCHAR(200) COMMENT '赠送留言',
    remark VARCHAR(500) COMMENT '备注',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_quota_id (quota_id),
    INDEX idx_ambassador_id (ambassador_id),
    INDEX idx_recipient_id (recipient_id),
    INDEX idx_usage_type (usage_type),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='名额使用记录表'`,

  // merit_points_records 表
  `CREATE TABLE IF NOT EXISTS merit_points_records (
    id INT AUTO_INCREMENT PRIMARY KEY COMMENT '记录ID',
    user_id INT NOT NULL COMMENT '用户ID',
    user_uid VARCHAR(64) COMMENT '用户UID',
    _openid VARCHAR(64) DEFAULT '' NOT NULL COMMENT 'CloudBase 用户标识（用于数据隔离）',
    type TINYINT NOT NULL COMMENT '类型：1获得/2使用/3过期/4退回',
    source TINYINT NOT NULL COMMENT '来源：1推荐初探班/2推荐密训班/3活动奖励/4商城兑换/5系统调整',
    amount DECIMAL(10,2) NOT NULL COMMENT '变动金额（正数增加，负数减少）',
    balance_after DECIMAL(10,2) COMMENT '变动后余额',
    order_no VARCHAR(32) COMMENT '关联订单号',
    exchange_no VARCHAR(32) COMMENT '关联兑换单号',
    referee_user_id INT COMMENT '被推荐人ID（推荐获得时）',
    referee_user_name VARCHAR(50) COMMENT '被推荐人姓名',
    activity_name VARCHAR(100) COMMENT '活动名称（活动奖励时）',
    remark VARCHAR(500) COMMENT '备注',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    INDEX idx_user_id (user_id),
    INDEX idx_type (type),
    INDEX idx_source (source),
    INDEX idx_order_no (order_no),
    INDEX idx_exchange_no (exchange_no),
    INDEX idx_created_at (created_at),
    INDEX idx_user_type (user_id, type),
    INDEX idx_user_source (user_id, source)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='功德分记录表'`,

  // cash_points_records 表
  `CREATE TABLE IF NOT EXISTS cash_points_records (
    id INT AUTO_INCREMENT PRIMARY KEY COMMENT '记录ID',
    user_id INT NOT NULL COMMENT '用户ID',
    user_uid VARCHAR(64) COMMENT '用户UID',
    _openid VARCHAR(64) DEFAULT '' NOT NULL COMMENT 'CloudBase 用户标识（用于数据隔离）',
    type TINYINT NOT NULL COMMENT '类型：1获得冻结/2解冻/3提现申请/4提现成功/5提现失败退回/6系统调整',
    amount DECIMAL(10,2) NOT NULL COMMENT '变动金额',
    frozen_after DECIMAL(10,2) COMMENT '变动后冻结余额',
    available_after DECIMAL(10,2) COMMENT '变动后可用余额',
    order_no VARCHAR(32) COMMENT '关联订单号',
    withdraw_no VARCHAR(32) COMMENT '关联提现单号',
    referee_user_id INT COMMENT '被推荐人ID（解冻时）',
    referee_user_name VARCHAR(50) COMMENT '被推荐人姓名',
    remark VARCHAR(500) COMMENT '备注',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    INDEX idx_user_id (user_id),
    INDEX idx_type (type),
    INDEX idx_order_no (order_no),
    INDEX idx_withdraw_no (withdraw_no),
    INDEX idx_created_at (created_at),
    INDEX idx_user_type (user_id, type)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='积分记录表'`,

  // withdrawals 表
  `CREATE TABLE IF NOT EXISTS withdrawals (
    id INT AUTO_INCREMENT PRIMARY KEY COMMENT '提现ID',
    withdraw_no VARCHAR(32) NOT NULL COMMENT '提现单号（格式：WD + 年月日 + 8位随机数）',
    user_id INT NOT NULL COMMENT '用户ID',
    user_uid VARCHAR(64) COMMENT '用户UID',
    user_name VARCHAR(50) COMMENT '用户姓名',
    _openid VARCHAR(64) DEFAULT '' NOT NULL COMMENT 'CloudBase 用户标识（用于数据隔离）',
    amount DECIMAL(10,2) NOT NULL COMMENT '提现金额',
    account_type TINYINT NOT NULL COMMENT '账户类型：1微信/2支付宝/3银行卡',
    account_info JSON NOT NULL COMMENT '账户信息',
    status TINYINT DEFAULT 0 COMMENT '状态：0待审核/1审核通过待转账/2已转账/3已拒绝',
    apply_time DATETIME NOT NULL COMMENT '申请时间',
    apply_ip VARCHAR(50) COMMENT '申请IP',
    audit_admin_id INT COMMENT '审核管理员ID',
    audit_time DATETIME COMMENT '审核时间',
    audit_remark VARCHAR(500) COMMENT '审核备注',
    reject_reason VARCHAR(500) COMMENT '拒绝原因',
    transfer_time DATETIME COMMENT '转账时间',
    transfer_no VARCHAR(64) COMMENT '转账流水号',
    transfer_admin_id INT COMMENT '转账操作管理员ID',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_withdraw_no (withdraw_no),
    INDEX idx_user_id (user_id),
    INDEX idx_status (status),
    INDEX idx_account_type (account_type),
    INDEX idx_apply_time (apply_time),
    INDEX idx_audit_time (audit_time),
    INDEX idx_audit_admin_id (audit_admin_id),
    INDEX idx_status_apply_time (status, apply_time)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='提现记录表'`,

  // ambassador_upgrade_logs 表
  `CREATE TABLE IF NOT EXISTS ambassador_upgrade_logs (
    id INT AUTO_INCREMENT PRIMARY KEY COMMENT '日志ID',
    user_id INT NOT NULL COMMENT '用户ID',
    user_uid VARCHAR(64) COMMENT '用户UID',
    from_level TINYINT NOT NULL COMMENT '原等级',
    to_level TINYINT NOT NULL COMMENT '新等级',
    upgrade_type TINYINT NOT NULL COMMENT '升级类型：1支付升级/2协议升级/3管理员调整',
    order_no VARCHAR(32) COMMENT '关联订单号（支付升级时）',
    contract_signature_id INT COMMENT '关联协议签署ID（协议升级时）',
    admin_id INT COMMENT '操作管理员ID（管理员调整时）',
    rewards JSON COMMENT '升级奖励信息',
    remark VARCHAR(500) COMMENT '备注',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '升级时间',
    INDEX idx_user_id (user_id),
    INDEX idx_from_level (from_level),
    INDEX idx_to_level (to_level),
    INDEX idx_upgrade_type (upgrade_type),
    INDEX idx_order_no (order_no),
    INDEX idx_created_at (created_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='大使升级日志表'`
];
